/**
 * STRATUM V3.0 — Swarm CLIENT: scheduled-universe search layer.
 *
 * ARCHITECTURE PIVOT (replaces the old trigger+poll model):
 *   On-demand hunt triggering is impossible on static GitHub Pages — there
 *   is no PAT in the browser, and git-push latency decouples the runner's
 *   disk from the polled raw.githubusercontent URL. So the swarm now runs
 *   on a 15-minute cron (.github/workflows/deploy-swarm.yml -> `scan-slate`)
 *   and commits ONE aggregate file: data/market_universe.json.
 *
 *   This module loads that file ONCE, caches it in module scope, and exposes
 *   pure client-side matching helpers. Typing = instant; ZERO network
 *   round-trips per hunt. There is deliberately NO startHunt() POST here —
 *   nothing in this file may issue a browser->workflow write.
 *
 * Backend contract (validated by schemas/market_universe.schema.json —
 * generated by scripts/swarm_runner.py scan-slate; DO NOT change shape):
 *   { generated_at_utc, next_refresh_estimate_utc, sources_status,
 *     fixture_count, fixtures: [ {fixture_id, home, away, sport, league,
 *     kickoff_utc, markets_scanned, top_edges[], agent_trace_lines[]} ] }
 */

/* ------------------------------------------------------------------ types */

export type SwarmAgent = 'SCOUT' | 'ACTUARY' | 'CONTEXT' | 'STRATEGIST';

/** Console/trace line as consumed by HunterConsole. SWARM = orchestrator. */
export interface HuntLine {
  agent: SwarmAgent | 'SWARM';
  text: string;
  ts: number; // seconds-into-cycle (backend logs relative time)
}

export type SourceStatus =
  | `ok(${number})`
  | 'blocked_by_waf'
  | 'timeout_on_load'
  | 'no_fixture_in_board'
  | 'deferred'
  | 'error'
  | (string & {});

/** One edge row — mirrors schemas/hunt_result.schema.json #/definitions/topEdge */
export interface TopEdge {
  market: string;
  selection: string;
  book_odds: number;
  fair_odds: number | null;
  ev_percent: number;
  confidence_score: number;
  kelly_stake_pct: number;
  reasoning_summary: string;
  best_bookmaker?: string;
  signals?: string[];
}

export interface UniverseFixture {
  fixture_id: string;
  home: string;
  away: string;
  sport: 'soccer' | 'nba' | 'nfl' | 'mlb' | 'nhl' | string;
  league: string;
  kickoff_utc: string;
  markets_scanned: number;
  top_edges: TopEdge[];
  agent_trace_lines: HuntLine[];
}

export interface MarketUniverse {
  schema_version?: string;
  generated_at_utc: string;
  next_refresh_estimate_utc: string;
  sources_status: Record<string, SourceStatus>;
  fixture_count: number;
  fixtures: UniverseFixture[];
  data_policy?: string;
  scan_stats?: Record<string, number>;
}

/** Legacy hunt report shape (still produced by single-hunt CLI/dev-server). */
export interface HuntResult {
  schema_version?: string;
  query: string;
  sport?: string;
  timestamp_utc: string;
  agents_executed: string[];
  agents_failed?: string[];
  markets_scanned_count: number;
  raw_prices_seen?: number;
  sources?: Record<string, string>;
  context_available?: boolean;
  mode?: string;
  top_edges: TopEdge[];
  visual_reports_png: string[];
  data_policy?: string;
  status: string;
  error_message?: string;
}

/** Replayable last-cycle console snapshot written by scan-slate. */
export interface HuntSnapshot {
  version?: string;
  query: string;
  sport: string;
  status: 'idle' | 'running' | 'complete' | 'no_results' | 'error';
  stage: string;
  progress: number;
  updated_at?: string;
  mode?: string;
  lines: HuntLine[];
  result: HuntResult | null;
  message?: string;
}

export class NetworkError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'NetworkError';
    Object.setPrototypeOf(this, NetworkError.prototype);
  }
}

/* ----------------------------------------------------------- configuration */

const GH_OWNER = 'petersidann';
const GH_REPO = 'Stratum';
const GH_BRANCH = 'main';

/** Canonical universe location (authoritative; refreshed every cron cycle). */
export const UNIVERSE_URL_RAW =
  `https://raw.githubusercontent.com/${GH_OWNER}/${GH_REPO}/${GH_BRANCH}/data/market_universe.json`;

/** Same-origin copy baked into the Pages deploy by deploy-swarm.yml.
 *  Tried FIRST so the app always matches the deployed bundle revision and
 *  survives raw.githubusercontent hiccups. */
export function universeUrlSameOrigin(): string {
  try {
    const base = new URL('.', window.location.href).href; // honors /Stratum/ subpath
    return `${base.replace(/\/$/, '')}/data/market_universe.json`;
  } catch {
    return './data/market_universe.json';
  }
}

export const STATUS_URL_RAW =
  `https://raw.githubusercontent.com/${GH_OWNER}/${GH_REPO}/${GH_BRANCH}/data/hunt_status.json`;

export function statusUrlSameOrigin(): string {
  try {
    const base = new URL('.', window.location.href).href;
    return `${base.replace(/\/$/, '')}/data/hunt_status.json`;
  } catch {
    return './data/hunt_status.json';
  }
}

/** Optional build-time override for local dev against the swarm dev server. */
function envOverrides(): { universe?: string; status?: string } {
  const env =
    (import.meta as unknown as { env?: Record<string, string | undefined> }).env ?? {};
  return { universe: env.VITE_UNIVERSE_URL, status: env.VITE_STATUS_URL };
}

/* ------------------------------------------------------------ normalization */

interface RawTraceLine {
  t?: number;
  ts?: number;
  agent?: string;
  msg?: string;
  text?: string;
}

export function normalizeLines(raw: unknown): HuntLine[] {
  if (!Array.isArray(raw)) return [];
  const out: HuntLine[] = [];
  for (const l of raw as RawTraceLine[]) {
    const text = typeof l.msg === 'string' ? l.msg : typeof l.text === 'string' ? l.text : '';
    if (!text) continue;
    const agentRaw = String(l.agent ?? 'SWARM').toUpperCase();
    const agent: HuntLine['agent'] =
      agentRaw === 'SCOUT' || agentRaw === 'ACTUARY' || agentRaw === 'CONTEXT' || agentRaw === 'STRATEGIST'
        ? agentRaw
        : 'SWARM';
    const ts = typeof l.ts === 'number' ? l.ts : typeof l.t === 'number' ? l.t : 0;
    out.push({ agent, text, ts });
  }
  return out;
}

function normalizeEdge(e: Record<string, unknown>): TopEdge {
  return {
    market: String(e.market ?? '?'),
    selection: String(e.selection ?? '?'),
    book_odds: Number(e.book_odds ?? 0),
    fair_odds: e.fair_odds === null || e.fair_odds === undefined ? null : Number(e.fair_odds),
    ev_percent: Number(e.ev_percent ?? 0),
    confidence_score: Number(e.confidence_score ?? 0),
    kelly_stake_pct: Number(e.kelly_stake_pct ?? 0),
    reasoning_summary: String(e.reasoning_summary ?? ''),
    ...(typeof e.best_bookmaker === 'string' ? { best_bookmaker: e.best_bookmaker } : {}),
    ...(Array.isArray(e.signals) ? { signals: e.signals.map(String) } : {}),
  };
}

function normalizeFixture(f: Record<string, unknown>): UniverseFixture {
  return {
    fixture_id: String(f.fixture_id ?? ''),
    home: String(f.home ?? 'HOME'),
    away: String(f.away ?? 'AWAY'),
    sport: String(f.sport ?? 'soccer'),
    league: String(f.league ?? ''),
    kickoff_utc: String(f.kickoff_utc ?? ''),
    markets_scanned: Number(f.markets_scanned ?? 0),
    top_edges: Array.isArray(f.top_edges) ? (f.top_edges as Record<string, unknown>[]).map(normalizeEdge) : [],
    agent_trace_lines: normalizeLines(f.agent_trace_lines),
  };
}

export function normalizeUniverse(json: unknown): MarketUniverse {
  const u = (json ?? {}) as Record<string, unknown>;
  const fixtures = Array.isArray(u.fixtures)
    ? (u.fixtures as Record<string, unknown>[]).map(normalizeFixture)
    : [];
  return {
    schema_version: u.schema_version as string | undefined,
    generated_at_utc: String(u.generated_at_utc ?? ''),
    next_refresh_estimate_utc: String(u.next_refresh_estimate_utc ?? ''),
    sources_status: (u.sources_status ?? {}) as Record<string, SourceStatus>,
    fixture_count: Number(u.fixture_count ?? fixtures.length),
    fixtures,
    data_policy: u.data_policy as string | undefined,
    scan_stats: u.scan_stats as Record<string, number> | undefined,
  };
}

export function normalizeSnapshot(json: unknown): HuntSnapshot {
  const s = (json ?? {}) as Record<string, unknown>;
  const status = String(s.status ?? 'idle') as HuntSnapshot['status'];
  return {
    version: s.version as string | undefined,
    query: String(s.query ?? ''),
    sport: String(s.sport ?? ''),
    status,
    stage: String(s.stage ?? status),
    progress: typeof s.progress === 'number' ? Math.min(Math.max(s.progress, 0), 1) : 0,
    updated_at: s.updated_at as string | undefined,
    mode: s.mode as string | undefined,
    lines: normalizeLines(s.lines),
    result: (s.result as HuntResult | null) ?? null,
    message: s.message as string | undefined,
  };
}

/* -------------------------------------------------------------- loaders   */

async function fetchFirst(urls: string[], signal?: AbortSignal): Promise<unknown> {
  let lastErr = 'no candidate URLs';
  for (const url of urls) {
    try {
      const res = await fetch(url, { cache: 'no-store', signal });
      if (!res.ok) {
        lastErr = `${url} -> HTTP ${res.status}`;
        continue;
      }
      return await res.json();
    } catch (e) {
      if ((e as Error)?.name === 'AbortError') throw e;
      lastErr = `${url} -> ${(e as Error).message}`;
    }
  }
  throw new NetworkError(`Unable to load Stratum data (${lastErr}).`);
}

let cachedUniverse: MarketUniverse | null = null;
let inflightUniverse: Promise<MarketUniverse> | null = null;

/**
 * Load data/market_universe.json ONCE (module-scoped cache). Concurrent
 * callers share a single in-flight request. Never triggers a hunt — this is
 * a read-only GET of a static committed artifact.
 */
export async function loadUniverse(signal?: AbortSignal): Promise<MarketUniverse> {
  if (cachedUniverse) return cachedUniverse;
  if (!inflightUniverse) {
    const ov = envOverrides();
    const urls = ov.universe
      ? [ov.universe]
      : [universeUrlSameOrigin(), UNIVERSE_URL_RAW];
    inflightUniverse = fetchFirst(urls, signal)
      .then((json) => {
        cachedUniverse = normalizeUniverse(json);
        return cachedUniverse;
      })
      .finally(() => {
        inflightUniverse = null;
      });
  }
  return inflightUniverse;
}

/** Force a re-GET (⟳ refresh); keeps the previous cache on failure. */
export async function refreshUniverse(signal?: AbortSignal): Promise<MarketUniverse> {
  const ov = envOverrides();
  const urls = ov.universe ? [ov.universe] : [universeUrlSameOrigin(), UNIVERSE_URL_RAW];
  const fresh = normalizeUniverse(await fetchFirst(urls, signal));
  cachedUniverse = fresh;
  return fresh;
}

/** Peek at the cached universe without touching the network. */
export function getCachedUniverse(): MarketUniverse | null {
  return cachedUniverse;
}

/** Replayable log of the LAST scheduled scan (read-only GET; not polling). */
export async function loadLastScan(signal?: AbortSignal): Promise<HuntSnapshot | null> {
  try {
    const ov = envOverrides();
    const urls = ov.status ? [ov.status] : [statusUrlSameOrigin(), STATUS_URL_RAW];
    return normalizeSnapshot(await fetchFirst(urls, signal));
  } catch (e) {
    if ((e as Error)?.name === 'AbortError') throw e;
    return null; // trace panel is optional garnish; universe is the product
  }
}

/* --------------------------------------------------- client-side matching */

const STOPWORDS = new Set([
  'vs', 'v', 'versus', 'the', 'fc', 'cf', 'sc', 'afc', 'club', 'team',
  'de', 'la', 'le', 'and',
]);

export function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // strip accents: Če → ce
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter((t) => t.length > 0 && !STOPWORDS.has(t));
}

function levenshtein(a: string, b: string): number {
  if (a === b) return 0;
  if (!a.length) return b.length;
  if (!b.length) return a.length;
  let prev = Array.from({ length: b.length + 1 }, (_, i) => i);
  for (let i = 1; i <= a.length; i++) {
    const cur = [i];
    for (let j = 1; j <= b.length; j++) {
      cur[j] = Math.min(
        prev[j] + 1,
        cur[j - 1] + 1,
        prev[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1),
      );
    }
    prev = cur;
  }
  return prev[b.length];
}

/** Fuzzy token similarity in [0,1]: exact=1, prefix=0.9, edit-distance≤2 scaled. */
function tokenSim(q: string, t: string): number {
  if (q === t) return 1;
  if (q.length > 2 && (t.startsWith(q) || q.startsWith(t))) return 0.9;
  const d = levenshtein(q, t);
  const maxLen = Math.max(q.length, t.length);
  if (d <= 2 && maxLen >= 3) return Math.max(0.55, 1 - d / maxLen);
  return 0;
}

/** Fixture match score in [0,1]: BOTH team sides must be plausibly present.
 *  Each side is scored as the BEST per-name-token match against the query
 *  tokens (not averaged over query tokens — a "vs" separator or stray word
 *  must never dilute an otherwise exact fixture name). */
export function fixtureScore(fixture: UniverseFixture, query: string): number {
  const qt = tokenize(query);
  if (!qt.length) return 0;
  const sideBest = (name: string): number => {
    const nameTokens = [...new Set(tokenize(name))];
    if (!nameTokens.length) return 0;
    let best = 0;
    for (const t of nameTokens) {
      let sim = 0;
      for (const q of qt) sim = Math.max(sim, tokenSim(q, t));
      best = Math.max(best, sim);
    }
    return best;
  };
  const h = sideBest(fixture.home);
  const a = sideBest(fixture.away);
  const both = Math.min(h, a);
  if (both < 0.4) return 0; // one-sided hits are noise, not a fixture match
  return 0.6 * both + 0.4 * Math.max(h, a);
}

export interface MatchResult {
  fixture: UniverseFixture;
  score: number;
}

/** Ranked matches for a free-text query, optionally pre-filtered by sport. */
export function searchFixtures(universe: MarketUniverse, query: string, sport = 'auto'): MatchResult[] {
  const pool =
    !sport || sport === 'auto' || sport === 'all'
      ? universe.fixtures
      : universe.fixtures.filter((f) => f.sport === sport);
  return pool
    .map((fixture) => ({ fixture, score: fixtureScore(fixture, query) }))
    .sort((x, y) => y.score - x.score);
}

/** Best fixture above the confidence floor, or null (→ nearest-fixtures UI). */
export function autoDetectFixture(universe: MarketUniverse, query: string, sport = 'auto'): MatchResult | null {
  const ranked = searchFixtures(universe, query, sport);
  const best = ranked[0];
  return best && best.score >= 0.55 ? best : null;
}

/** Top-N plausible alternatives for the NO-MATCH card (score ≥ 0.25). */
export function nearestFixtures(universe: MarketUniverse, query: string, n = 5, sport = 'auto'): MatchResult[] {
  return searchFixtures(universe, query, sport).filter((m) => m.score >= 0.25).slice(0, n);
}

/** Sports actually present in the slate (for the selector's dynamic counts). */
export function sportsInUniverse(universe: MarketUniverse): string[] {
  return [...new Set(universe.fixtures.map((f) => f.sport))].sort();
}

/** Human age label for "last scheduled scan @ …" stamps. */
export function scanAgeLabel(generatedAtUtc: string, nowMs = Date.now()): string {
  const t = Date.parse(generatedAtUtc);
  if (!Number.isFinite(t)) return 'unknown age';
  const mins = Math.max(0, Math.round((nowMs - t) / 60000));
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins} min ago`;
  const hrs = Math.floor(mins / 60);
  return `${hrs}h ${mins % 60}m ago`;
}
