import React, { useEffect, useState, useCallback } from "react";
import Dashboard from "./components/Dashboard.jsx";
import Charts from "./components/Charts.jsx";

const AUTO_REFRESH_MS = 60_000; // data is regenerated by GHA every ~5 min

/** Resolve the URL for a repo-root data file.
 *  Priority: ?dataBase=<url> override → VITE_DATA_URL env → raw.githubusercontent
 *  derived from window.location (works both on Pages and when previewing the
 *  built dist/ folder locally). */
function dataUrl(file) {
  const params = new URLSearchParams(window.location.search);
  let base = params.get("dataBase");
  if (!base && import.meta.env.VITE_DATA_URL) base = import.meta.env.VITE_DATA_URL;
  if (!base) {
    const segs = window.location.pathname.split("/").filter(Boolean);
    const repo = segs[0]; // owner already lives in the hostname
    const host = window.location.hostname;
    if (host.endsWith("github.io") && repo) {
      const owner = host.split(".")[0];
      base = `https://raw.githubusercontent.com/${owner}/${repo}/main/data`;
    } else {
      base = "/data"; // same-origin fallback (repo served statically)
    }
  }
  return `${base.replace(/\/$/, "")}/${file}?t=${Math.floor(Date.now() / 30000)}`;
}

async function fetchJson(file) {
  const res = await fetch(dataUrl(file), { cache: "no-store" });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${file}`);
  return res.json();
}

export default function App() {
  const [scan, setScan] = useState(null);
  const [stats, setStats] = useState(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    try {
      // Portfolio stats failing must never blank the board: fetch independently.
      const [scanDoc, statsDoc] = await Promise.all([
        fetchJson("latest_scan.json"),
        fetchJson("portfolio_stats.json").catch(() => null),
      ]);
      setScan(scanDoc);
      if (statsDoc) setStats(statsDoc);
      setError("");
    } catch (err) {
      setError(String(err?.message || err));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
    const id = setInterval(load, AUTO_REFRESH_MS);
    return () => clearInterval(id);
  }, [load]);

  const degraded = scan && scan.status !== "live";

  return (
    <div className="min-h-screen bg-stratum-bg text-gray-100">
      {/* Header */}
      <header className="sticky top-0 z-10 border-b border-stratum-border bg-stratum-panel/95 backdrop-blur">
        <div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 px-4 py-3">
          <h1 className="text-lg font-black tracking-[0.3em] text-stratum-accent">
            STRATUM
            <span className="ml-2 text-xs font-medium tracking-normal text-stratum-muted">
              QUANT ENGINE · GHOST SERVER
            </span>
          </h1>
          <div className="flex items-center gap-3">
            <span
              className={`rounded-full border px-3 py-1 text-xs font-bold uppercase tracking-wider ${
                degraded
                  ? "border-stratum-warn/50 text-stratum-warn"
                  : "border-stratum-accent/50 text-stratum-accent"
              }`}
            >
              {degraded ? "Sample / Degraded" : "Live"}
            </span>
            <button
              onClick={load}
              className="min-h-touch rounded-md border border-stratum-border bg-stratum-bg px-4 text-xs font-bold uppercase tracking-widest hover:border-stratum-accent hover:text-stratum-accent"
            >
              ⟳ Refresh
            </button>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-7xl space-y-6 px-4 py-6">
        {loading && !scan && (
          <p className="py-20 text-center text-stratum-muted">Loading market data…</p>
        )}

        {error && !scan && (
          <div className="rounded-lg border border-stratum-danger/50 bg-stratum-danger/10 p-4 text-sm text-stratum-danger">
            Could not reach <code>data/latest_scan.json</code>. Has the{" "}
            <strong>Stratum Market Scanner</strong> workflow run yet? ({error})
          </div>
        )}

        {error && scan && (
          <div className="rounded-lg border border-stratum-warn/50 bg-stratum-warn/10 p-3 text-xs text-stratum-warn">
            Partial refresh failure: {error} — showing last good data.
          </div>
        )}

        {scan && (
          <>
            {degraded && (
              <div className="rounded-lg border border-stratum-warn/50 bg-stratum-warn/10 p-3 text-xs font-semibold text-stratum-warn">
                ⚠ DATA SOURCE: SAMPLE / DEGRADED — live feeds unavailable this
                run. Prices shown are labeled synthetic demo data, never real quotes.
              </div>
            )}
            <Dashboard scan={scan} />
            <Charts scan={scan} stats={stats} />
            <footer className="pb-8 pt-4 text-center text-xs text-stratum-muted">
              Generated {scan.generated_at} · Logic in Actions, UI in Pages ·
              Zero server-side rendering
            </footer>
          </>
        )}
      </main>
    </div>
  );
}
